import Logo from "./components/Logo";
import Navigation from "./components/Navigation";
export const metadata = {
  title: "The Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
        </header>
        <main>
          <Navigation />
          {children}
        </main>
        <footer>The Copyright by Di Dan</footer>
      </body>
    </html>
  );
}
