import Header from "./_components/Header";
import "@/app/_styles/globals.css";
import { Josefin_Sans } from "next/font/google";
const josefin = Josefin_Sans({
  subsets: ["latin", "vietnamese"],
  display: "fallback",
});
export const metadata = {
  title: {
    template: "%s | The Wild Oasis",
    default: "The Wild Oasis",
  },
  description: "Generated by Next.js",
};

import { ReservationProvider } from "@/app/_components/ReservationContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} min-h-screen bg-primary-950 text-primary-100 flex flex-col relative`}
      >
        <Header />
        <div className="flex-1 px-8 py-12 grid">
          <main className="max-w-7xl mx-auto w-full">
            <ReservationProvider>
              {children}
              {/* Có thể bọc Context Provider vào Server Components, miễn SC được truyền vào dạng children(props) và không được sử dụng hooks */}
            </ReservationProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
